#repository: "OWASP/www-chapter-okinawa"
remote_theme: "owasp/www--site-theme"
github: [metadata]
plugins:
  - jekyll-include-cache-0.2.0
exclude:
  - .github/
  - .vscode/
  - vendor/
  - .gitignore
  - .markdownlint.json
  - LICENSE
  - README.md
