name: Jekyll site CI

on:
  # push:
  #   branches-ignore:
  #     - master
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set environment
        run: |
          echo "repository: ${{ github.repository }}" >> ${{ github.workspace }}/_config.yml

      - name: Cache Gems
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/vendor/bundle
          key: v2-bundle-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            v2-bundle-${{ runner.os }}-

      # chmodを消すと権限エラーになるので消さないこと。
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
            -v ${{ github.workspace }}:/srv/jekyll \
            -v ${{ github.workspace }}/vendor/bundle:/usr/local/bundle \
            jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
